apiVersion: v1
kind: Service
metadata:
  name: isp-config-service-internal
spec:
  clusterIP: None
  publishNotReadyAddresses: True
  selector:
    app: isp-config-service
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: isp-config-service
spec:
  selector:
    app: isp-config-service
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001