apiVersion: v1
kind: Service
metadata:
  name: isp-config-service-internal
spec:
  clusterIP: None
  publishNotReadyAddresses: True
  selector:
    app: isp-config-service
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: isp-config-service
spec:
  selector:
    app: isp-config-service
  ports:
    - protocol: TCP
      name: ws
      port: 9001
      targetPort: 9001
    - protocol: TCP
      name: grpc
      port: 9002
      targetPort: 9002