// Code generated by "stringer -type=Command -output const_string.go"; DO NOT EDIT.

package cluster

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UpdateBackendDeclarationCommand-1]
	_ = x[DeleteBackendDeclarationCommand-2]
	_ = x[UpdateConfigSchemaCommand-3]
	_ = x[ModuleConnectedCommand-4]
	_ = x[ModuleDisconnectedCommand-5]
	_ = x[DeleteModulesCommand-6]
	_ = x[DeleteVersionConfigCommand-7]
	_ = x[ActivateConfigCommand-8]
	_ = x[DeleteConfigsCommand-9]
	_ = x[UpsertConfigCommand-10]
	_ = x[DeleteCommonConfigsCommand-11]
	_ = x[UpsertCommonConfigCommand-12]
	_ = x[BroadcastEventCommand-13]
}

const _Command_name = "UpdateBackendDeclarationCommandDeleteBackendDeclarationCommandUpdateConfigSchemaCommandModuleConnectedCommandModuleDisconnectedCommandDeleteModulesCommandDeleteVersionConfigCommandActivateConfigCommandDeleteConfigsCommandUpsertConfigCommandDeleteCommonConfigsCommandUpsertCommonConfigCommandBroadcastEventCommand"

var _Command_index = [...]uint16{0, 31, 62, 87, 109, 134, 154, 180, 201, 221, 240, 266, 291, 312}

func (i Command) String() string {
	i -= 1
	if i >= Command(len(_Command_index)-1) {
		return "Command(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Command_name[_Command_index[i]:_Command_index[i+1]]
}
